version: "3.7"
services:

    #Laravel App
    app:
        build:
            args:
                user: maruan
                uid: 1000
            context: ./
            dockerfile: ./docker/Dockerfile
        image: laravel-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - mynetwork

    #Nginx Service
    nginx:
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - 8000:80
        volumes:
            - ./:/var/www
            - ./docker/nginx:/etc/nginx/conf.d/
        networks:
            - mynetwork
    #Mysl Service
    db:
        image: mysql:8
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_ROOT_PASSWORD: hailuong1012
        ports:
            - "3307:3306"
        networks:
            - mynetwork

networks:
    mynetwork:
        driver: bridge
